// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnLNzIMd3fN7_kT2zTuU6AD5Or2YdfyI',
    appId: '1:852446547520:web:2234ad6878c182205299a5',
    messagingSenderId: '852446547520',
    projectId: 'iquote-2ebbe',
    authDomain: 'iquote-2ebbe.firebaseapp.com',
    databaseURL: 'https://iquote-2ebbe-default-rtdb.firebaseio.com',
    storageBucket: 'iquote-2ebbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BcBNDhmmIx3HRtfyCt_dIL4Q11U17Rs',
    appId: '1:852446547520:android:891bd2deb8a56e805299a5',
    messagingSenderId: '852446547520',
    projectId: 'iquote-2ebbe',
    databaseURL: 'https://iquote-2ebbe-default-rtdb.firebaseio.com',
    storageBucket: 'iquote-2ebbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNGOgHoKTVkoLKXIWXg2ucA3gWVAfwI1c',
    appId: '1:852446547520:ios:211931e85da34bf75299a5',
    messagingSenderId: '852446547520',
    projectId: 'iquote-2ebbe',
    databaseURL: 'https://iquote-2ebbe-default-rtdb.firebaseio.com',
    storageBucket: 'iquote-2ebbe.appspot.com',
    iosBundleId: 'com.example.idea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNGOgHoKTVkoLKXIWXg2ucA3gWVAfwI1c',
    appId: '1:852446547520:ios:55aaa806544809f95299a5',
    messagingSenderId: '852446547520',
    projectId: 'iquote-2ebbe',
    databaseURL: 'https://iquote-2ebbe-default-rtdb.firebaseio.com',
    storageBucket: 'iquote-2ebbe.appspot.com',
    iosBundleId: 'com.example.idea.RunnerTests',
  );
}
